storage:
  endpoint: https://oss.wfy.gov110.cn
  supplier_code: "360"
  env: dev
  inbox_bucket:
  outbox_bucket:
  aksk_file: secret/360-aksk.txt
  ca_file: secret/wfy-root-ca.pem
  verify_tls: true

runtime:
  data_dir: data
  max_tasks: 0
  poll_interval_seconds: 60
  task_deadline_seconds: 3600
  upload: true
  overwrite_local: false
